version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile 
    container_name: my_dotnet_app
    ports:
      - "8080:80" 
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DB_SERVER=mysql
      - DB_NAME=Blockchain
      - DB_USER=root
      - DB_PASS=1234qwer
      - REDIS_SERVER=redis
    depends_on:
      - mysql
      - redis
    networks:
      - app-network

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-network

  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234qwer
    ports:
      - "3306:3306"
    volumes:
      - ./DbScheme/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - app-network


networks:
  app-network:
    driver: bridge
